services:
  - type: web
    name: typing-trainer-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_FIRST_NAME
        sync: false
      - key: DJANGO_SUPERUSER_LAST_NAME
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: POSTGRES_DB
        fromDatabase:
          name: typing-trainer-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: typing-trainer-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: typing-trainer-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: typing-trainer-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: typing-trainer-db
          property: port

  - type: web
    name: typing-trainer-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    previews:
      generation: automatic
    routes:
      - type: rewrite
        source: /api/*
        destination: https://typing-trainer-backend.onrender.com/api/*
      - type: rewrite
        source: /media/*
        destination: https://typing-trainer-backend.onrender.com/media/*
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: typing-trainer-db
    plan: free
