TEXT_TYPE_QUOTE = 'quote'
TEXT_TYPE_CUSTOM = 'custom'
TEXT_TYPE_NONSENSE = 'nonsense'
TEXT_TYPE_RANDOM_WORDS = 'words'
TEXT_TYPE_USER = 'user'
TEXT_TYPE_REPLAY = 'replay'
DEFAULT_TEXT_TYPE = TEXT_TYPE_QUOTE
MODE_STANDARD = 'standard'

DEFAULT_TEXT_SIZE = 40
QUOTE_MIN_SIZE = 1
TEXT_MIN_SIZE = 10
TEXT_MAX_SIZE = 600

TRAINING_SESSION_TTL_SECONDS = 45 * 60
MAX_ALLOWED_WPM = 260
MAX_ALLOWED_CPM = 1600
MAX_RESULT_TIME_DRIFT_SECONDS = 12
