TEXT_TYPE_QUOTE = 'quote'
TEXT_TYPE_CUSTOM = 'custom'
TEXT_TYPE_NONSENSE = 'nonsense'
TEXT_TYPE_RANDOM_WORDS = 'words'
TEXT_TYPE_USER = 'user'
DEFAULT_TEXT_TYPE = TEXT_TYPE_QUOTE
MODE_STANDARD = 'standard'

DEFAULT_TEXT_SIZE = 40
QUOTE_MIN_SIZE = 1
TEXT_MIN_SIZE = 10
TEXT_MAX_SIZE = 600
