# Generated by Django 5.2 on 2026-04-24

import django.db.models.deletion
import trainer.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_seed_default_texts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('training_text', models.TextField(blank=True, default='')),
                ('text_type', models.CharField(default='quote', max_length=16)),
                ('mode', models.CharField(default='standard', max_length=16)),
                ('requested_size', models.PositiveIntegerField(default=0)),
                ('is_personal_text', models.BooleanField(default=False)),
                ('client_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=trainer.models.get_training_session_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='trainer.language')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
                ('user_text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='trainer.usertext')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
